### ISSUE TITLE
V2 Configuration Reloading Checklist

### ISSUE THREAD

**Issue by michalpristas** [elastic/elastic-agent#1056]
Before merging V2 branch we need to make sure other functionality introduced/used in previous model works as expected today:

- [ ] reloading proxy settings, all clients are using desired proxy config
- [x] reloading download config, upgrade downloads agent from desired path
- [x] reloading monitoring config, when config changes monitoring is shut down/altered
- [ ] reloading log level, beats and agent are unable to reload log level on the fly make sure it still works
- [x] reloading artifact config is still functional (sourceURI, timeouts, drop path)
- [x] make sure included config files make sense and agent consumes/parses them correctly

These should be verified, in case feature does not work let's create separate issue and link it to this one. 

cc @blakerouse 

### 🔴 handle proxy change 
no UI option 

### 🔴 handle artifact config change 
no UI option

### 🔴 reloading log level
always injecting debug, as per spec, linked to #221 

### 🔴 handle source_uri change
not included, should be in next main merge

### 🔴 handle proxy change
not included, should be in next main merge

### 🔴 handle artifact config change
not included, should be in next main merge

**Comment by michalpristas** [comment]
updated description with test results I made today

**Comment by michalpristas** [comment]
seems ok so far. i'm closing this in case we face some issues after big main merge we will deal with them separately
