### ISSUE TITLE
[META] Elastic Agent V2 Architecture

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-agent#189]
Meta issue to publicly track Elastic Agent V2 progress.

Actual V2 architecture design.
![image](https://user-images.githubusercontent.com/43535167/157623504-2da434e1-5eb2-4190-9bb5-ac419a143d5e.png)

Related repository: https://github.com/elastic/elastic-agent-shipper

## Goals

- Reduce the number of connections required by Elastic Agent to Elasticsearch or other remote services.
- Reduce the complexity of the inputs
- Reduce the memory usage
- Easier debugging
 - Single logging from all the components.
 - Better introspection of the running processes.

## Development Plan

Elastic Agent preparation phase:

- [ ] https://github.com/elastic/elastic-agent-client/issues/32

- [ ] **Phase 1:** 
  - [ ] Beta:  Shipper is available for Filebeat and Metricbeat by turning a feature flag.
  - [ ] GA: Shipped is used by default with Filebeat and Metricbeat under Agent.
- [ ] **Phase 2**: Integrate with the security solution: 
  - [ ] Endpoint security.
  - [ ] Security beats: 
    - [ ] packetbeat
    - [ ] auditbeat
    - [ ] winlogbeat
    - [ ] osquerybeat
- [ ] **Phase 3**: Migrate remaining beats and agent inputs
  - [ ] [APM server](https://github.com/elastic/apm-server)
  - [ ] Heartbeat
  - [ ] [Cloudbeat](https://github.com/elastic/cloudbeat)
- [ ] **Phase 4**
  - [ ] Run a process per input type.

### Phase 1: Separate the shipper from Filebeat and Metricbeat under Agent. (See https://github.com/elastic/elastic-agent-shipper/issues/3)

The goal is to reduce the number of connections for Filebeat and Metricbeat instances to remote services.

- [x] https://github.com/elastic/elastic-agent/issues/215
- [x] https://github.com/elastic/elastic-agent/issues/216
- [x] https://github.com/elastic/elastic-agent/issues/217
- [ ] https://github.com/elastic/elastic-agent/issues/218
- [x] https://github.com/elastic/elastic-agent/issues/219
- [x] https://github.com/elastic/elastic-agent/issues/88
- [x] https://github.com/elastic/elastic-agent/issues/221
- [x] https://github.com/elastic/elastic-agent/issues/222

### Phase 2: Integrate with Endpoint security & the Security beats.

The goal is to move a uniform output strategy.
- https://github.com/elastic/elastic-agent/issues/220

### Phase 3: 
- [x] Run a process per input type: https://github.com/elastic/obs-dc-team/issues/699

## QA / Testing Needs
- [ ] New end to end tests:
  - [ ] TBD.
  - [ ] Add a test where the agent is configured to use the shipper from startup.
  - [ ] Add a test where the agent is configured not to use the shipper at startup, then switched over to it.
- [ ] Performance testing:
- [ ] New manual QA tests:
  - [ ] TBD. At minimum the agent must be regression tested on each supported OS with the shipper enabled. 

## Documentation
The following documentation tasks should be accomplished at a minimum:

- [ ] Document the change in the logging
- [ ] Document the usage for the feature flag  (environment or via elastic agent policy)
- [ ] Document the new global processing options.

## Target

- Definition / Design: 8.2
- Beta: 8.4/8.5
- GA: TBD

**Comment by pierrehilbert** [comment]
Closing this one as v2 architecture has been released in 8.6
