### ISSUE TITLE
[META] Support the Elastic Agent Data Shipper

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#214]
The Elastic agent must be capable of starting the Elastic agent data shipper and connecting inputs to it. The data shipper implementation is tracked under https://github.com/elastic/elastic-agent-shipper/issues/3

To support the phase 1 data shipper the agent must complete at least the following tasks:

- [ ] Integrate the shipper into the elastic agent packaging step.
- [ ] Define a feature flag for enabling the shipper in the agent policy, defaulting to false.
- [ ] Start the shipper process(es) and configure inputs to write to them when the shipper feature flag is enabled.
  - [ ] The agent policy's output configuration section must be provided to the shipper. 
    - [ ] The agent policy's output section must be updated to allow configuring the shipper queue(s). 
  - [ ] The number of shippers to start will be determined based on the number of outputs requested and their configuration. There is a one to one mapping between outputs and shipper processes initially.

**Comment by cmacknz** [comment]
I created https://github.com/elastic/elastic-agent-shipper/issues/53 to discuss the configuration the agent will need to provide to each shipper instance it starts.

**Comment by blakerouse** [comment]
We need to discuss how we want to implement a solution for #1476.
