### ISSUE TITLE
[Cloud Native] Use Kustomize to deploy resources

### ISSUE THREAD

**Issue by gizas** [elastic/elastic-agent#2175]
## What is the goal?
Use Kustomize to deploy manifests.

## Why is this important?
Currently, multiple manifests file are used to deploy similar resources. As a better alternative, we should put in separate files everything that is common to them, and build overlays for unique specifications. Kustomize allows us to do that. It is supported since [kubectl 1.14 version](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/), which makes it unnecessary to install new tools.

## Steps to achieve this

- [ ] Use Kustomize to deploy elastic agent
   - [ ]  Update the manifests from [`elastic-agent/dev-tools/kubernetes`](https://github.com/elastic/elastic-agent/tree/main/dev-tools/kubernetes)
     - [ ] [Standalone] Create a new overlay for Red Hat Openshift 
     - [ ] [Standalone] Create option to enable hints instead of making the user uncomment what it is needed
      - [ ] [Managed]  Create new overlays for GKE/EKS/AWS
        - [ ] Support GKE Autopilot scenarios (https://github.com/elastic/elastic-agent/blob/autopilotdocumentaton/docs/elastic-agent-gke-autopilot.md)
      - [ ] Support deployment installation of cluster-wide metrics (kube-state and kube-API)
      - [ ] Support local installations with `ssl.verification_mode:none` patching
      - [x] [Both] Create overlay for managed and standalone mode - [PR here](https://github.com/elastic/elastic-agent/pull/2104)
      - [x] [Both] Deploy kube state metrics at the same elastic agent is deployed - [PR here](https://github.com/elastic/elastic-agent/pull/2104)
   - [ ] Sync the manifests from [`elastic-agent/dev-tools/kubernetes`](https://github.com/elastic/elastic-agent/tree/main/dev-tools/kubernetes) with the manifests from [`elastic-agent/deploy/kubernetes`](https://github.com/elastic/elastic-agent/tree/main/deploy/kubernetes)
      - [ ] [In discussion] Remove the use of [Makefile](https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/Makefile)
   - [ ] Update [the documentation](https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html)
- [ ] Use Kustomize to deploy manifests needed for testing Kubernetes integration - [issue here](https://github.com/elastic/elastic-package/issues/1102)
  - [ ] Document this change
- [ ] Use Kustomize to deploy beats - [issue here](https://github.com/elastic/beats/issues/33514)
  - [ ] Add kustomize to beats/dev-tools/kubernetes. Try to move shared resources to `common` folder
    - [ ] Create overlays for each beat (eg. filebeat, metricbeat, ...)
    - [ ] Support deployment installation of cluster-wide metrics (kube-state and kube-API)
    - [ ] Support hints autodiscovery in beats with new overlay
    - [ ] Support of cloud.id and cloud.auth variables
    - [ ] Support local installations with `ssl.verification_mode:none` patching
    - [ ] Deploy kube state metrics at the same time beats is deployed
  - [ ] Sync the manifests from `beats/dev-tools/kubernets` to `beats/deploy/kubernetes`(https://github.com/elastic/beats/tree/main/deploy/kubernetes)
    - [ ] Remove the use of Makefile in `beats/deploy/kubernetes`
  - [ ] Update the documentation [[Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/running-on-kubernetes.html), [Mericbeat](https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-kubernetes.html)]
- [ ] Investigate use of kustomize to enforce order of manifest to solve [issue](https://github.com/elastic/integrations/issues/4874) with nginx-ingress-controller system tests

**Comment by mitodrummer** [comment]
Would it be possible for an integration to dynamically provide it's own kustomize overlays. e.g to define required mount points and or set the elastic-agent as 'privileged'? This is in relation to PR #2259 . Cheers!

**Comment by gsantoro** [comment]
> Would it be possible for an integration to dynamically provide it's own kustomize overlays. e.g to define required mount points and or set the elastic-agent as 'privileged'? This is in relation to PR #2259 . Cheers!

hello @mitodrummer,
as far as I understand, there is no way for an integration to affect k8s or the environment it runs on. Not even elastic agent is able to do that. For example, the integration for Kubernetes currently has a dependency on kube-state-metrics and we are planning to have that installed via Kustomize when we install the elastic-agent.
