### ISSUE TITLE
[Meta][Feature] Start the shipper process(es) and configure inputs to write to them when the shipper feature flag is enabled.

### ISSUE THREAD

**Issue by ph** [elastic/elastic-agent#219]
Dependency on #218 

- [x] Start a shipper for each unique destination used by Filebeat or Metricbeat.
- [x] Supervise and monitor the shipper processes.
- [x] Use the shipper as the output destination for Filebeat and Metricbeat
- [x] Collect health information about the shipper

**Comment by cmacknz** [comment]
Heartbeat needs some special accommodation when implementing this, they always need the Elasticsearch output configuration even when writing events through the shipper.

- [ ] https://github.com/elastic/elastic-agent/issues/1476

**Comment by blakerouse** [comment]
@jlind23 Yes sorry forgot to close it.

**Comment by jlind23** [comment]
No worries, thanks @blakerouse
