### ISSUE TITLE
[Meta][Feature] Refactor how Elastic Agent know how to run a binary.

### ISSUE THREAD

**Issue by ph** [elastic/elastic-agent#222]
Our [spec](https://github.com/elastic/elastic-agent/tree/main/internal/spec) defines how software is run by the Elastic Agent and what transformation the transpiler needs to execute to convert the configuration from an Agent configuration to a beats configuration. Change are required for the Elastic Agent to understand what is a shipper.

We would like to make the following changes.

- [x] Allow the Specification to ship with the binaries instead of embedding it.
- [x] Investigate how Elastic Agent could trust the file. 
- [x] Investigate how Elastic Agent could trust the binary
- [x] Document the fields in the file.
- [x] Validate the different fields of the file. (json schema or golang struct)
  - [x] If field is not present we should fails.
- [x] Allow the file to support multiple entrypoint (`process filestream`, `process tcp`)

**Comment by ph** [comment]
#  Formats
## Proposal 1
### Example 1 - For filebeat

```yaml
version: v2
services:
  - name: filestream
    entrypoint: filebeat filestream
    type: input
  - name: logfile
    entrypoint: filebeat logfile
    type: input
  - name: elasticsearch:
    type: shipper
    entrypoint: shipper elasticsearch
# done at build time
checksum:
signature:
```

### Example 2 - For Metricbeat
 TBD

### Example 3 - For Endpoint
```yaml
version: v2
services:
 - name: endpoint
   constraints: not (${runtime.arch} == 'arm64' and ${runtime.family} == 'redhat' and ${runtime.major} == '7')
   type: input
   check_install:
   - exec_file:
       path: "endpoint-security"
       args:["verify"] ["--log"] ["stderr"]
       timeout: 30
   post_install:
   - exec_file:
       path: "endpoint-security"
       args:
       - "install"
       - "--log"
       - "stderr"
       - "--upgrade"
       - "--resources"
       - "endpoint-security-resources.zip"
       timeout: 600
   pre_uninstall:
   - exec_file:
       path: "endpoint-security"
       args:
         - "uninstall"
         - "--log"
         - "stderr"
       timeout: 600
```

## Proposal 2
```yaml
version: v2
inputs:
  filestream:
    entrypoint: filebeat filestream
  logfile:
    entrypoint: filebeat logfile
shippers:
  elasticsearch: shipper elasticsearch
checksum:
signature:
```

## Build work flow

```sh
cd $BTS
make release

distributions/${platform}-${arch}/inputs-x
distributions/${platform}-${arch}/inputs-x.yml

# cd $ELASTIC-AGENT
# Task done:
#  - Validates the spec for each binary
#  - Add checksum to yaml
#  - Sign the YML

AGENT_DROP=$BTS/distributions/,$CLOUDBEAT/distributions make release
```
## Trust
TBD

**Comment by ph** [comment]
After discussing with @blakerouse  we are looking at proposal 2, I am going to redo the above to make it more clearer and send it for review.

**Comment by ph** [comment]
I've send the proposal to review, will update this issue with the conclusion.

**Comment by ph** [comment]
This the above work was done in the v2 specification proposal and in the feature-v2-arch branch.
