### ISSUE TITLE
[META] Testing scenarios for Elastic Agent E2E testing framework

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-agent#2428]
This issue will act as a placeholder which contains a list of all the E2E testing scenarios that should be implemented as part of the Elastic Agent E2E testing framework.

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/elastic-agent/issues/2641
- [ ] https://github.com/elastic/elastic-agent/issues/2176
- [ ] elastic/elastic-agent#2429
- [ ] elastic/elastic-agent#2430
- [ ] elastic/elastic-agent#2431
- [ ] elastic/elastic-agent#2432
- [ ] https://github.com/elastic/ingest-dev/issues/1652
- [x] https://github.com/elastic/ingest-dev/issues/1455
- [ ] https://github.com/elastic/elastic-agent/issues/2402
- [x] https://github.com/elastic/elastic-agent/issues/1174
- [ ] https://github.com/elastic/elastic-agent/issues/1357
- [ ] https://github.com/elastic/elastic-agent/issues/1399
- [x] Include an E2E test that emulates an air gapped installation without external connectivity.
- [ ] elastic/fleet-server#2484
- [ ] #2482
- [ ] #2501
- [ ] https://github.com/elastic/elastic-agent/issues/2705
- [ ] https://github.com/elastic/elastic-agent/issues/2948
```
- [ ] Add an end to end test to ensure the agent can process actions, including signed actions. The simplest example is the settings action to change the log level. For the signed actions (as of March 7, 2023), the only actions that can be signed by kibana are the endpoint actions. The agent validates the signature for all ```INPUT_ACTION``` types of actions though, so potentially one could sign osquery actions outside of the kibana if they want.
Also there are two things that are getting signed: 1) protection configuration of the policy 2) input actions. For comprehensive testing of all the error cases the tests would need to explore the cases where the signed policy configuration or the signed  actions are being tempered with, such as: invalid signature validation key, corrupted signed data, policy id mismatch for the policy signed data, action id and the agent id mismatch for the action signed data. Basically tests different types of tampering use cases.

**Comment by jlind23** [comment]
@pierrehilbert can you make sure this list is complete and that all test cases are planned for one of the upcoming sprint?

**Comment by cmacknz** [comment]
Added https://github.com/elastic/elastic-agent/issues/2705

**Comment by cmacknz** [comment]
Added https://github.com/elastic/elastic-agent/issues/2948

**Comment by ycombinator** [comment]
Closing in favor of individual issues for pending tests: 

> Add an end to end test to ensure the agent can process actions, including signed actions. The simplest example is the settings action to change the log level. For the signed actions (as of March 7, 2023), the only actions that can be signed by kibana are the endpoint actions. The agent validates the signature for all INPUT_ACTION types of actions though, so potentially one could sign osquery actions outside of the kibana if they want.
> Also there are two things that are getting signed: 1) protection configuration of the policy 2) input actions. For comprehensive testing of all the error cases the tests would need to explore the cases where the signed policy configuration or the signed actions are being tempered with, such as: invalid signature validation key, corrupted signed data, policy id mismatch for the policy signed data, action id and the agent id mismatch for the action signed data. Basically tests different types of tampering use cases.

https://github.com/elastic/elastic-agent/issues/5216

> Create tests to ensure that Elastic Agent's upgrade are working as expected

https://github.com/elastic/elastic-agent/issues/5217
https://github.com/elastic/elastic-agent/issues/5219
https://github.com/elastic/elastic-agent/issues/5218
