### ISSUE TITLE
[Meta] Improving Hints Autodiscovery with Elastic Agent

### ISSUE THREAD

**Issue by gizas** [elastic/elastic-agent#3063]
## Synopsis

Hints based Autodiscovery for Elastic Agent has been released as beta since 8.5. Information about the functionality and configuration of this feature can be found [here](https://www.elastic.co/guide/en/fleet/master/hints-annotations-autodiscovery.html) 

This is the Meta issue that tries to summarise a list of enhancements, bug fixes and documentation updates we have gathered so far in order to improve the general UX and functionality of Hints based Autodiscovery.

## List of Issues

- [ ] https://github.com/elastic/package-storage-infra/issues/479
- [ ] https://github.com/elastic/elastic-agent/issues/2959
- [ ] https://github.com/elastic/elastic-agent/issues/3057
- [ ] https://github.com/elastic/elastic-agent/issues/3062

**Comment by ChrsMark** [comment]
Added https://github.com/elastic/elastic-agent/issues/3158 after discussed at https://github.com/elastic/elastic-agent/issues/2959 with @gsantoro.

**Comment by cmacknz** [comment]
We are starting to look at https://github.com/elastic/elastic-agent/issues/2460 where the root problem is that the agent configurations generated by autodiscovery are gigantic when it is configured to monitor all the pods on a node or all the nodes in a cluster.

We haven't decided on a solution yet, so the exact impact isn't known. I don't expect it to affect any of the work here, but wanted to note it here for visibility anyway since it may affect how agent autodiscovery generates configurations.

**Comment by ChrsMark** [comment]
@gizas sth also related to this feature: https://github.com/elastic/elastic-agent/issues/2200
