### ISSUE TITLE
Introduce log message for not supported annotations for Hints based autodiscover of Elastic Agent

### ISSUE THREAD

**Issue by gizas** [elastic/elastic-agent#3064]
**Describe the enhancement:**

[Hints annotation based autodiscover](https://www.elastic.co/guide/en/fleet/master/hints-annotations-autodiscovery.html) is based on specific annotations that are provided on pods. In more details, the hints mechanism looks for hints in Kubernetes Pod annotations that have the prefix co.elastic.hints.  But what if the user specifies an annotation that is not supported or with a typo, this means that no extra configuration will be applied and the autodiscovery will fail with no errors although users will believe that they have configured  everything correctly. 

This enhancement will compare the provided annotations against a specific list of supported values and will return 

**Describe a specific use case for the enhancement or feature:**

One of the basic annotations is `co.elastic.hints/host`: Specifies The host to use for metrics retrieval. We had configured our pod with a typo so the annotation provided was `co.elastic.hints/hosts`. We lost time trying troubleshooting why this was happening. But if we had a message in logs eg. `co.elastic.hints/hosts is not recognised as supported annotation`, this would help us troubleshoot quicker

**What is the definition of done?**

- Introduce the code that will check the provided annotations against the supported list
- Provide test evidence that enhancement is working
- Introduce a new test to log specific message
- Document any new informations for the users on the 'Troubleshooting' section of Hints Autodiscover page

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/beats/pull/38213
- [ ] https://github.com/elastic/elastic-agent/pull/4360
- [ ] https://github.com/elastic/elastic-agent-autodiscover/pull/81
- [ ] https://github.com/elastic/elastic-agent-autodiscover/pull/83
- [ ] https://github.com/elastic/elastic-agent-autodiscover/pull/89#issuecomment-2058534331
```
