### ISSUE TITLE
[Meta] Supprting Kerberos in Elastic Agent Kafka  modules 

### ISSUE THREAD

**Issue by nimarezainia** [elastic/elastic-agent#4824]
Currently there are gaps in agent/beats support for kerberos in various kafka implementations. This meta issue is to gather all the specific development efforts that need to be implemented in order to provide a cohesive offering

```tasklist

- [ ] Update the Kafka client currently in use by beats/agent so that we have access to the latest
- [ ] Ensure filebeat Kafka input correctly authenticates against Active Directory using Kerberos config
- [ ] Ensure *beats output to Kafka authenticates against Active Directory using Kerberos config, and make this feature GA
- [ ] Modify the Fleet UI for Kafka output to include a Kerberos configuration
- [ ] (optional) Support kerberos authentication on the Metricbeat kafka module

```

**Comment by cmacknz** [comment]
The first step here will be getting a test environment with both Kafka and Kerberos using Active Directory. 

We can then test if we can fix this by upgrading our fork of https://github.com/elastic/sarama which implements our Kafka client. This is quite far (~700 commits) behind upstream now. There is an upstream Kerberos test we could use as a starting point https://github.com/IBM/sarama/blob/main/kerberos_client_test.go. This appears to have been added in https://github.com/IBM/sarama/pull/2457.

We can simulataneously evaluate if it is worth continuing to maintain our own fork of Sarama, or even evaluate alternative client packages, although that will present challenges with configuration backwards compatibility. https://github.com/twmb/franz-go is one alternative that claims Kerberos support.

**Comment by ycombinator** [comment]
Moving this to the beats repo as the majority of the work is over there.
