### ISSUE TITLE
[Meta] Elastic Agent setup

### ISSUE THREAD

**Issue by narph** [elastic/elastic-agent#59]
Repo setup tasks

- [x] .CI setup (fleet-ci)
- [x] Unified release 
- [x] e2e testing https://github.com/elastic/elastic-agent/pull/54
- [x] Rebase, previous beats automations
- [ ] Changelog https://github.com/elastic/elastic-agent/issues/47
- [ ] Pinned version for the upstream dependencies (filebeat, metricbeat) while working with snapshots
- [x] Validate release process still applies  https://github.com/elastic/observability-dev/blob/main/docs/dc/releases.md
- [x] Update documentation  https://github.com/elastic/observability-docs/pull/1620 https://github.com/elastic/infra/pull/34859
- [x] Update license
- [x] Enable mergify https://github.com/elastic/infra/issues/34835
- [x] Alert control plane team for any elastic agent related PR's in the beats repo https://github.com/elastic/beats/pull/30618
- [x] Switch 8.2 snapshots to new repo https://github.com/elastic/infra/pull/34951
- [x] Remove elastic-agent directory from beats https://github.com/elastic/beats/pull/30559 
- [x] Move `elastic-agent` related issues from the beats repo to the new `elastic-agent` repo
- [x] Update developer documentation (Usage of `EXTERNAL`, Expected directory layout, Usage of `DEV`)
- [x] Move out of beats deploy/kube/elastic agent templates https://github.com/elastic/beats/pull/31103, https://github.com/elastic/observability-docs/issues/1743

**Comment by v1v** [comment]
What's the OS support to be executed in the CI? So far, it runs on:
- ubuntu
- arm
- windows-2019
- `macos` but in GitHub actions

Windows-2022 support has been added in https://github.com/elastic/elastic-agent/pull/62 but, what's the strategy? Is it needed? If so, when should it run?

**Comment by ph** [comment]
Added a new item to this meta issue: `Update developer documentation (Usage of EXTERNAL, Expected directory layout, Usage of DEV)`

**Comment by jlind23** [comment]
Closing this as done.
