### ISSUE TITLE
[Meta] V2 Feature Architecture (8.5/8.6)

### ISSUE THREAD

**Issue by blakerouse** [elastic/elastic-agent#836]
## Overview

This is a meta issue to track all the items that need to be completed before the Elastic Agent is fully running and working with the new V2 architecture design. This issue tracks both the items that need to be done by the control plane team as well as other teams that interact with the Elastic Agent.

### Control Plane

* [x] Implement new v2 input specification
* [x] Use the v2 input specification to generate the runtime model (aka. what should be running based on policy and v2 input specification)
* [x] Refactor component binaries to be pre-extracted inside components directory with v2 specification
* [x] Implement the v2 command runtime (runs each sub-process)
* [x] Implement the v2 runtime manager (takes the computed runtime model and works to reconcile the model to the actual state)
* [x] Implement the v2 server-side for the v2 control protocol
* [x] Connect subprocess to Elastic Agent stdout/stderr
* [x] Implement coordinator to manage config changes, variables (from composable inputs), and send it to the runtime manager.
* [x] Refactor state tracking to use the coordinator as a central location of state management for the Elastic Agent.
* [x] Use the new v2 runtime manager for standalone mode
* [x] Use the new v2 runtime manager for Fleet mode
* [x] Update the `inspect` command to provide inspection for the v2 runtime
* [x] Update Fleet Server to use the new v2 control protocol
  * Owner: @blakerouse 
* [x] Use the new v2 runtime manager for Fleet Server Bootstrap
  * Owner: @blakerouse 
* [x] https://github.com/elastic/elastic-agent/issues/100
* [x] Add support for service based components (aka. Endpoint) https://github.com/elastic/elastic-agent/issues/1069
  * Owner: @aleksmaus 
* [x] Determine path forward for metrics: https://github.com/elastic/elastic-agent/issues/954
  * Owner: @michalpristas 
* [x] Determine path forward for diagnostics: https://github.com/elastic/elastic-agent/pull/1140
  * Owner: @blakerouse 
* [ ] Fix running monitoring filebeat and metricbeat to send logs and metrics of running components to elasticsearch (https://github.com/elastic/elastic-agent/issues/221)
* [x] Verify configuration reloading continues to work: https://github.com/elastic/elastic-agent/issues/1056
* [x] Implement `HasStrictExecPerms` for Windows: https://github.com/elastic/elastic-agent/pull/1061#discussion_r959949534
* [ ] https://github.com/elastic/elastic-agent/issues/1275

#### Known V2 issues

* [x] V2: Agent doesn't stop cleanly on SIGINT: https://github.com/elastic/elastic-agent/issues/995
* [x] https://github.com/elastic/elastic-agent/pull/1258
* [x] V2: Agent policy change is not applied properly and requires agent restart: https://github.com/elastic/elastic-agent/issues/996
* [x] V2: Agent starting multiple instances of filebeat or metricbeat and goes into tight restart loop for the beat process:
https://github.com/elastic/elastic-agent/issues/997
* [x] V2: Elastic Agent Install is broken. https://github.com/elastic/elastic-agent/issues/1125 
* [x] https://github.com/elastic/elastic-agent/issues/1159
* [x] https://github.com/elastic/beats/issues/33125

### Data Plane

* [x] Migrate libbeat agent management to the agent V2 control protocol (https://github.com/elastic/beats/issues/32078)
  * Owner: @fearful-symmetry 
* [x] Beats run under agent should start without reading a configuration file from disk. (https://github.com/elastic/beats/issues/31901)
  * Owner: @fearful-symmetry 
* [ ] https://github.com/elastic/beats/issues/32993
* [x] https://github.com/elastic/beats/issues/33135
* [x] https://github.com/elastic/beats/issues/33168

### Security

* [x] Implement V2 control protocol in Endpoint Security
  * Status: blocked on https://github.com/elastic/elastic-agent/issues/1069 
  * Owner: @softengchick @brian-mckinney 
* [x] Implement V2 control protocol in Cloudbeat: https://github.com/elastic/cloudbeat/pull/364
  * Status: Done, pending merge and more testing.
  * Owner: @eyalkraft 
* [x] Implement V2 control protocol in Osquerybeat:
  * [x] Done in in https://github.com/elastic/beats/pull/32673
  * Owner: @fearful-symmetry 
* [x] Implement V2 control protocol in Packetbeat and Auditbeat:
  * Status: blocked on https://github.com/elastic/beats/pull/32673
  * [x] https://github.com/elastic/beats/issues/32786
  * Owner: @fearful-symmetry & @andrewkroh 

### Observability

* [x] APM Server: https://github.com/elastic/apm-server/issues/8958
  * Status: Done, pending merge.
  * Owner: @axw 
* [x] Heartbeat: https://github.com/elastic/beats/pull/33405
  * Status: Done
  * Owner: @fearful-symmetry & @emilioalvap 

### Shipper Support

* [x] Add v2 output specification for shipper support: https://github.com/elastic/elastic-agent-shipper/pull/126
* [x] Add shipper component runtime model calculation (when shipper enabled by environment) (includes calculating its configuration with processors from connected inputs) 
  * [x] https://github.com/elastic/elastic-agent/issues/214
    * Owner: @blakerouse 
    * [x] https://github.com/elastic/elastic-agent/issues/217
    * [x] https://github.com/elastic/elastic-agent/issues/219
    * [ ] https://github.com/elastic/elastic-agent/issues/1476 
* [x] Add shipper GRPC credential generation to runtime manager (connects inputs to shipper)

#### Packaging Shipper and Inputs

* [x] Create build pipelines and packaging steps for new Elastic Agent Input and Shipper components (https://github.com/elastic/elastic-agent/issues/592)
  * Status: in progress
  * Owner: @narph 
  * [x] https://github.com/elastic/release-eng/issues/268
  * [x] https://github.com/elastic/release-eng/issues/283

**Comment by cmacknz** [comment]
Closing, everything remaining is now tracked as a bug against the release issue.
